### ISSUE TITLE
`group.previous` should always point at latest messages

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-group-exclusion-spec#11]
> 4.1.3.A. the tangles.group.previous field MUST be epoch G's ID

That's not how the group tangle works. That tangle keeps track of every message that's part of a group, and therefore the `group.previous` would point at the latest message(s) in the previous epoch(s). @mixmix and I agreed that it would make sense to have an additional tangle here, maybe called `epoch` that keeps track of group/epoch init messages.

**Comment by staltz** [comment]
Oh, I messed it up. Yeah I don't understand tangles that well. Please take ownership (together with @mixmix) of anything tangles-related in this spec.
