### ISSUE TITLE
`group.root` can only be null at the root itself

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-group-exclusion-spec#12]
> 4.1.3.C. if G is epoch zero, tangles.group.root MUST be epoch G's ID

I guess depends on what you mean an "epoch ID" is but `group.root` won't be able to be the root msg id nor the group id, since both those are only known after publishing the root. That's why it's set to null in the spec

**Comment by staltz** [comment]
Oh yeah, this was a brain fart. Well spotted. I fixed it now.

**Comment by staltz** [comment]
No wait, I think what I fixed is also wrong, because `G` here refers to the *previous* epoch, while `H` is the current (or "next") epoch. I don't know what to write in 4.1.3.C. but as I said in #11, feel free to make sense of this tangles thing.
