### ISSUE TITLE
Specify how replication works

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-group-exclusion-spec#2]
We need to make it clear that:

- Every member in an epoch needs to replicate all other members' epochs feeds from previous epochs, to preserve conversations. EXCEPT (see next point):
- An excluded member's group/epoch feed should not be replicated by peers anymore (in fact, we should replicate all the old ones and refuse to replicate new messages, so we need some kind of indicator of what message sequence was the last one, when the member is excluded, and we probably need a little schema for the exclusion msg)

**Comment by Powersource** [comment]
> what message sequence was the last one, when the member is excluded, and we probably need a little schema for the exclusion msg)

ooh that's a very good point/idea. I was wondering how to limit them from adding new stuff to the tangle

**Comment by staltz** [comment]
Important context: https://github.com/ssbc/ssb-ebt/issues/79

**Comment by staltz** [comment]
Fixed with section 4.7.
