### ISSUE TITLE
Specify lexicographic winner rule

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-group-exclusion-spec#7]

**Comment by Powersource** [comment]
As I wrote in #1:

I think we probably can't make it un-gameable, but maybe we could make it harder than simply trivial. Right now as you say, making a key starting with 0000 would make you win basically every time, no matter the keys the others publish. But maybe we could require knowing all the other keys to be able to game it. Pseudocode!

```js
keys = [array of the keys]
keys_hash = hash(keys.join(""))
hash_as_num = Integer(keys_hash)
winning_key = keys[hash_as_num % keys.length]
```

**Comment by staltz** [comment]
Perhaps there is a way to make it un-gameable. Like, with lexicographic order, you almost always know that `00000000` is very strong, but that's just because you know what the absolute minimum "element" is (`0`). What if the smallest number is not known *until* you know who to compare it with?

Like here's a strawman:

Take the epoch key `Lk` for epoch `L` and the epoch key `Rk` for epoch `R`.  If `Lk xor Rk < 0x7f`, then `L` wins. "0x7f" is the hexadecimal lexicographic "middle" byte, so that given any random byte as hex, there 50% chance it's < 0x7f. This way, you don't know if `Lk` wins over `Rk` before you know what `Rk` is. And even if it's a strong winner, there's no guarantee it will win over some other `Xk`.

cc @arj03

**Comment by staltz** [comment]
I played around with code and notepad, and came up with a pretty okay rule!

* if L<X<R then L wins
* if R<X<L then R wins
* if X<L<R then L wins
* if X<R<L then R wins
* if R<L<X then L wins
* if L<R<X then R wins

where X = xor(L, R).

We know that given 3 items to compare (X,L,R) there are only 6 permutations, and there's a balanced case of 3 wins for each L and R. Since they don't know what the xor is until they discover each other, they can't "pre-mine" good bytes that will win. And what works against one "opponent" won't work against another opponent, because the xors are different in that case.

Here's some JS code that you can run in Node.js to experiment with the above:

<details>
<summary>click here</summary>

```js
const crypto = require('crypto');

function xor(bufA, bufB) {
  const result = Buffer.alloc(bufA.length);
  for (let i = 0; i < bufA.length; i++) {
    result[i] = bufA[i] ^ bufB[i];
  }
  return result;
}

const L = crypto.randomBytes(1);
const R = crypto.randomBytes(1);
const X = xor(L, R);

function print(a, b, c, d) {
  const names = [];
  if (a === L) names.push('L');
  else if (a === R) names.push('R');
  else names.push('xor');
  if (b === L) names.push('L');
  else if (b === R) names.push('R');
  else names.push('xor');
  if (c === L) names.push('L');
  else if (c === R) names.push('R');
  else names.push('xor');
  let winner = '';
  if (d === L) winner = 'L';
  else if (d === R) winner = 'R';
  else winner = 'xor';
  console.log(names.join(' < '));
  console.log(
    a.toString('hex'),
    '<',
    b.toString('hex'),
    '<',
    c.toString('hex'),
  );
  console.log(winner + ' wins!');
}

const LR = L.compare(R) < 0;
const RL = !LR;
const XL = X.compare(L) < 0;
const LX = !XL;
const XR = X.compare(R) < 0;
const RX = !XR;
if (LX && XR) print(L, X, R, L);
else if (RX && XL) print(R, X, L, R);
else if (XL && LR) print(X, L, R, L);
else if (XR && RL) print(X, R, L, R);
else if (RL && LX) print(R, L, X, L);
else if (LR && RX) print(L, R, X, R);
```

</details>

**Comment by staltz** [comment]
Hmm, no I'm not sure this winning strategy is "balanced" with respect to all possible combinations of L and R.

**Comment by staltz** [comment]
Specifically, here's how often each byte wins over every other byte, using the 6-rules idea I shared before:

<details>
<summary>click here</summary>

```
00 wins 0.4%
01 wins 50.0%
02 wins 50.4%
03 wins 49.6%
04 wins 51.2%
05 wins 50.4%
06 wins 49.6%
07 wins 48.8%
08 wins 52.7%
09 wins 52.0%
0a wins 51.2%
0b wins 50.4%
0c wins 49.6%
0d wins 48.8%
0e wins 48.0%
0f wins 47.3%
10 wins 55.9%
11 wins 55.1%
12 wins 54.3%
13 wins 53.5%
14 wins 52.7%
15 wins 52.0%
16 wins 51.2%
17 wins 50.4%
18 wins 49.6%
19 wins 48.8%
1a wins 48.0%
1b wins 47.3%
1c wins 46.5%
1d wins 45.7%
1e wins 44.9%
1f wins 44.1%
20 wins 62.1%
21 wins 61.3%
22 wins 60.5%
23 wins 59.8%
24 wins 59.0%
25 wins 58.2%
26 wins 57.4%
27 wins 56.6%
28 wins 55.9%
29 wins 55.1%
2a wins 54.3%
2b wins 53.5%
2c wins 52.7%
2d wins 52.0%
2e wins 51.2%
2f wins 50.4%
30 wins 49.6%
31 wins 48.8%
32 wins 48.0%
33 wins 47.3%
34 wins 46.5%
35 wins 45.7%
36 wins 44.9%
37 wins 44.1%
38 wins 43.4%
39 wins 42.6%
3a wins 41.8%
3b wins 41.0%
3c wins 40.2%
3d wins 39.5%
3e wins 38.7%
3f wins 37.9%
40 wins 74.6%
41 wins 73.8%
42 wins 73.0%
43 wins 72.3%
44 wins 71.5%
45 wins 70.7%
46 wins 69.9%
47 wins 69.1%
48 wins 68.4%
49 wins 67.6%
4a wins 66.8%
4b wins 66.0%
4c wins 65.2%
4d wins 64.5%
4e wins 63.7%
4f wins 62.9%
50 wins 62.1%
51 wins 61.3%
52 wins 60.5%
53 wins 59.8%
54 wins 59.0%
55 wins 58.2%
56 wins 57.4%
57 wins 56.6%
58 wins 55.9%
59 wins 55.1%
5a wins 54.3%
5b wins 53.5%
5c wins 52.7%
5d wins 52.0%
5e wins 51.2%
5f wins 50.4%
60 wins 49.6%
61 wins 48.8%
62 wins 48.0%
63 wins 47.3%
64 wins 46.5%
65 wins 45.7%
66 wins 44.9%
67 wins 44.1%
68 wins 43.4%
69 wins 42.6%
6a wins 41.8%
6b wins 41.0%
6c wins 40.2%
6d wins 39.5%
6e wins 38.7%
6f wins 37.9%
70 wins 37.1%
71 wins 36.3%
72 wins 35.5%
73 wins 34.8%
74 wins 34.0%
75 wins 33.2%
76 wins 32.4%
77 wins 31.6%
78 wins 30.9%
79 wins 30.1%
7a wins 29.3%
7b wins 28.5%
7c wins 27.7%
7d wins 27.0%
7e wins 26.2%
7f wins 25.4%
80 wins 99.6%
81 wins 98.8%
82 wins 98.0%
83 wins 97.3%
84 wins 96.5%
85 wins 95.7%
86 wins 94.9%
87 wins 94.1%
88 wins 93.4%
89 wins 92.6%
8a wins 91.8%
8b wins 91.0%
8c wins 90.2%
8d wins 89.5%
8e wins 88.7%
8f wins 87.9%
90 wins 87.1%
91 wins 86.3%
92 wins 85.5%
93 wins 84.8%
94 wins 84.0%
95 wins 83.2%
96 wins 82.4%
97 wins 81.6%
98 wins 80.9%
99 wins 80.1%
9a wins 79.3%
9b wins 78.5%
9c wins 77.7%
9d wins 77.0%
9e wins 76.2%
9f wins 75.4%
a0 wins 74.6%
a1 wins 73.8%
a2 wins 73.0%
a3 wins 72.3%
a4 wins 71.5%
a5 wins 70.7%
a6 wins 69.9%
a7 wins 69.1%
a8 wins 68.4%
a9 wins 67.6%
aa wins 66.8%
ab wins 66.0%
ac wins 65.2%
ad wins 64.5%
ae wins 63.7%
af wins 62.9%
b0 wins 62.1%
b1 wins 61.3%
b2 wins 60.5%
b3 wins 59.8%
b4 wins 59.0%
b5 wins 58.2%
b6 wins 57.4%
b7 wins 56.6%
b8 wins 55.9%
b9 wins 55.1%
ba wins 54.3%
bb wins 53.5%
bc wins 52.7%
bd wins 52.0%
be wins 51.2%
bf wins 50.4%
c0 wins 49.6%
c1 wins 48.8%
c2 wins 48.0%
c3 wins 47.3%
c4 wins 46.5%
c5 wins 45.7%
c6 wins 44.9%
c7 wins 44.1%
c8 wins 43.4%
c9 wins 42.6%
ca wins 41.8%
cb wins 41.0%
cc wins 40.2%
cd wins 39.5%
ce wins 38.7%
cf wins 37.9%
d0 wins 37.1%
d1 wins 36.3%
d2 wins 35.5%
d3 wins 34.8%
d4 wins 34.0%
d5 wins 33.2%
d6 wins 32.4%
d7 wins 31.6%
d8 wins 30.9%
d9 wins 30.1%
da wins 29.3%
db wins 28.5%
dc wins 27.7%
dd wins 27.0%
de wins 26.2%
df wins 25.4%
e0 wins 24.6%
e1 wins 23.8%
e2 wins 23.0%
e3 wins 22.3%
e4 wins 21.5%
e5 wins 20.7%
e6 wins 19.9%
e7 wins 19.1%
e8 wins 18.4%
e9 wins 17.6%
ea wins 16.8%
eb wins 16.0%
ec wins 15.2%
ed wins 14.5%
ee wins 13.7%
ef wins 12.9%
f0 wins 12.1%
f1 wins 11.3%
f2 wins 10.5%
f3 wins 9.8%
f4 wins 9.0%
f5 wins 8.2%
f6 wins 7.4%
f7 wins 6.6%
f8 wins 5.9%
f9 wins 5.1%
fa wins 4.3%
fb wins 3.5%
fc wins 2.7%
fd wins 2.0%
fe wins 1.2%
ff wins 0.4%
```

</details>

**Comment by staltz** [comment]
Chart of the probability of a byte to win if the 6-rule has `X = xor(L,R)`:

![Screenshot from 2023-02-16 11-01-03@2x](https://user-images.githubusercontent.com/90512/219317791-1b88823b-98f8-4714-86e9-fe37cf5b70dc.png)


Chart of the probability of a byte to win if the 6-rule has `X = sha256(xor(L,R))`:

![Screenshot from 2023-02-16 11-00-57@2x](https://user-images.githubusercontent.com/90512/219317821-51855380-a68f-44aa-99aa-7f00eaee86f1.png)

**Comment by staltz** [comment]
And just for completion, here is the chart for our currently naive `L < R` winner rule:

![Screenshot from 2023-02-16 11-06-57@2x](https://user-images.githubusercontent.com/90512/219319085-c869f9ee-c0c6-4ba2-a79d-c5a792c3d441.png)

**Comment by Powersource** [comment]
> Perhaps there is a way to make it un-gameable. Like, with lexicographic order, you almost always know that 00000000 is very strong, but that's just because you know what the absolute minimum "element" is (0). What if the smallest number is not known until you know who to compare it with?

Yes that's what I meant with my example, it would be un-gameable until you know the other messages, after which it will be gameable unless we add a blockchain or something.

What do you think of my pseudocode above? I think it should give equal probability to all the keys.

**Comment by staltz** [comment]
Oh, sorry, now I understand what you meant and the pseudocode. Turns out your suggestion is pretty good! All bytes have ~50% chance of winning. Works for me, should we settle on it?

![Screenshot from 2023-02-16 14-37-34@2x](https://user-images.githubusercontent.com/90512/219366941-55622619-6de7-45f9-a01f-b241d7ffa838.png)

**Comment by Powersource** [comment]
Sure
