### ISSUE TITLE
Replication of excluded member

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-group-exclusion-spec#9]
> 4.7.2.A. a SHOULD cease fetching messages from group feeds of other epochs X belonging to a member that was excluded from X, but should continue to fetch messages from group feeds belonging to any remaining member of X. See figure 9 as an example.

If you miss messages then from excluded member C, then you'll both have an incomplete tangle (e.g. maybe missing comments in a thread) and maybe incomplete group state updates such as member exclusions/additions. That sounds undesirable.

@staltz

**Comment by staltz** [comment]
But it was a requirement that we identified in the "Brainstorming Group Removals" hackmd:

> * members of the group
>   A. cannot see what  Oscar is posting anymore
>   B. know person was removed
>   C. stop replicating new messages on the Oscar’s group feed

**Comment by Powersource** [comment]
I agree we should stop replicating Oscar from some point onward, but I also think peers should agree where that point is and that the point shouldn't be random for every peer based on how far they had replicated at the time. So that peers don't end up with different datasets.

**Comment by staltz** [comment]
Oh, now I see, you mean that we should be more specific with the sequence number where a peer "ceases" to fetch message.

Yes I agree and that's tied with #10
